version: '3.8'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - 4318:4318
      - 4317:4317
      - 6831:6831/udp
      - 16686:16686
      - 14250:14250
      - 14268:14268
      - 5778:5778
    environment:
      - COLLECTOR_OTLP_ENABLED=true
