version: '3'
services:
  dscp-node:
    image: digicatapult/dscp-node:v10.0.0-chore_upgrade-deps
    command: |
      --base-path /data/
      --dev
      --unsafe-rpc-external
      --rpc-cors all
    ports:
      - 30333:30333
      - 9944:9944
      - 9933:9933
    restart: on-failure
